include(":battery")
include(":connectivity")
include(":ignore-ios")
include(":ignore-junit")
include(":ignore-junit5")
include(":package-info")
include(":samples:shared")
include(":samples:androidApp")
