name: Build

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

  build:
    needs: [validation]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '17'
            cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: konan cache
        uses: actions/cache@v4
        with:
            path: ~/.konan
            key: ${{ runner.os }}-konan

      - name: Check
        run: ./gradlew check

      - name: Build
        run: ./gradlew build -x check -x lintVitalRelease

      - name: Prepare tag properties
        run: |
          echo "${{secrets.GPG_SIGNING_SECRET_KEY_RING_FILE_BASE64}}" > ~/.gradle/sonatype-appmattus-keys.gpg.b64
          base64 -d ~/.gradle/sonatype-appmattus-keys.gpg.b64 > ~/.gradle/sonatype-appmattus-keys.gpg
          echo "${{secrets.GPG_GRADLE_PROPERTIES}}" > ~/.gradle/gradle.properties
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload tag
        run: ./gradlew publishAllPublicationsToMavenCentral -Psigning.secretKeyRingFile=$(echo ~/.gradle/sonatype-appmattus-keys.gpg)
        if: startsWith(github.ref, 'refs/tags/')
